### PR TITLE
Add YOURLS as a candidate for "auto-update"

### PR DESCRIPTION
**Pull request by LeoColomb**
Should we? 😃 
Thanks! (and thanks for @J0WI for the suggestion).

### CODE REVIEW

**Comment by yosifkit** [comment]
Unfortunately this won't work as-is.  The design of the auto-update bot is to only commit changes to files and not add new files/directories and never to delete, while the design of the `update.sh` script in the `docker-yourls` repo is to create a new folder for the most recent version (which I then assume the old directories need to be manually deleted with `git rm -r`).

**Comment by LeoColomb** [comment]
@yosifkit Ah, I see. That said that structure is not that relevant for yourls, so I just simplified it (see https://github.com/YOURLS/docker-yourls/pull/18), to avoid strong version-relative structure.

Then is this more relevant?

Thanks again!

**Comment by yosifkit** [comment]
I think that should work. :+1: 

cc @tianon

**Comment by tianon** [comment]
LGTM :+1: :heart:

So, just to make sure expectations are clear, this _only_ automates the commits to https://github.com/YOURLS/docker-yourls -- a PR to https://github.com/docker-library/official-images is still required.  If you'd like, I'm willing to include those in my own PRs to https://github.com/docker-library/official-images for library-maintained images, but otherwise we'll assume you'll still be making those. :smile:

**Comment by tianon** [comment]
https://doi-janky.infosiftr.net/job/update.sh/job/yourls/1/console :+1:

**Comment by LeoColomb** [comment]
@tianon Thanks! Got it for the still manual part, let's keep it manual for now.

**Comment by LeoColomb** [comment]
> but otherwise we'll assume you'll still be making those.

@tianon I can't... 😢 
I don't have the permission.

> Pull request creation failed. Validation failed: You can't perform that action at this time.

**Comment by tianon** [comment]
Do you get a "New pull request" button on `yourls` when you visit https://github.com/docker-library-bot/official-images/branches/all ?  What if you hit https://github.com/docker-library-bot/official-images/compare/yourls?expand=1 or https://github.com/docker-library-bot/official-images/pull/new/yourls directly?

I'm pretty sure we've had someone external open from those branches before, but now you've got me second-guessing whether that's the case. :sweat_smile:

**Comment by LeoColomb** [comment]
> https://github.com/docker-library-bot/official-images/branches/all

image

---

> https://github.com/docker-library-bot/official-images/compare/yourls?expand=1

Are you sure?

image

---

> https://github.com/docker-library-bot/official-images/pull/new/yourls

image

**Comment by yosifkit** [comment]
It makes sense in retrospect, but apparently you can't open a PR unless you have write access to that branch. 🙄 I also thought someone had used the bot's branches to make PR's but I can't find any.

> Note: To open a pull request in a public repository, you must have write access to the head or the source branch or, for organization-owned repositories, you must be a member of the organization that owns the repository to open a pull request.
>
>\- https://help.github.com/en/articles/creating-a-pull-request

I went ahead and opened the update for yourls (https://github.com/docker-library/official-images/pull/6699)

**Pull request merged**
